services:
  db:
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_USER: absys
      POSTGRES_PASSWORD: absys
      POSTGRES_DB: absys
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U absys"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - ENV=docker
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
    driver: local
