FROM ubuntu:20.04

ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -y

RUN apt-get install -y --no-install-recommends ssh sudo
RUN apt install python-is-python3 -y
RUN apt install python3-pip -y
RUN pip install --upgrade pip
RUN pip install --upgrade certifi

#python3
RUN apt-get install -y python3.8-dev python3.8-venv

# deps
RUN apt-get install -y build-essential gettext
RUN apt-get install -y libpq-dev
RUN apt-get install -y libxslt1-dev
#RUN apt-get install -y libtiff5-dev #(bereits in Ubuntu vorhanden?)
RUN apt-get install -y libjpeg-dev
RUN apt-get install -y zlib1g-dev libfreetype6-dev
RUN apt-get install -y liblcms2-dev
#Pongo FIX
RUN apt-get install -y libpangocairo-1.0-0

#RUN apt-get install -y libwebp-dev #(bereits in Ubuntu vorhanden?)

#apatche
#RUN apt-get install -y apt-utils vim curl 
RUN apt-get install -y apache2 apache2-utils

#uWISGI
RUN apt-get -y install python3 libapache2-mod-wsgi-py3


#Kopieren der Config Files
ADD ./000-default.conf /etc/apache2/sites-available/000-default.conf
ADD ./wsgi.conf /etc/apache2/conf-available/wsgi.conf

#Apatche Module starten
RUN a2enmod headers
RUN a2enmod ssl

#User hinzufügen
RUN useradd --create-home -s /bin/bash vagrant

#venv anlegen
#USER vagrant
#RUN python3 -m venv ~/pyvenv

USER root
#Ordner anlegen
RUN mkdir -p /home/vagrant/media/
RUN mkdir -p /home/vagrant/pyvenv
RUN mkdir -p home/vagrant/static_root/
RUN chmod -R 755 /home/vagrant

#Apatche Seite Aktivieren
RUN a2ensite 000-default

#uWSGI Konfig Laden
RUN a2enconf wsgi

#Wheelhouse laden
ADD ./wheelhouse /home/vagrant/wheelhouse

#install.sh laden
ADD ./install.sh /home/vagrant

#run.sh laden
ADD ./run.sh /home/vagrant

USER root
RUN chmod u+x /home/vagrant/run.sh

#install.sh Starten
RUN /home/vagrant/install.sh

#USER vagrant
EXPOSE 443

ENV DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost,172.19.0.5
ENV DEFAULT_DATABASE_URL=postgres://absys:absys@localhost/absys

#um den Server zu starten; um den Container am Laufen zu halten
CMD /home/vagrant/run.sh; apache2ctl  -D FOREGROUND