FROM ubuntu:22.04

ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -y

# Add PostgreSQL repository
RUN  apt-get install curl -y
RUN  apt-get install gpg -y
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
RUN apt update -y

# Install PostgreSQL 16
RUN apt install postgresql-client-16 -y

# Install CRON
RUN apt-get install cron -y

# Install wichtiges Zeug halt
RUN apt-get install nano -y

# Crontab file copied to cron.d directory.
COPY cronjob /etc/cron.d/container_cronjob

RUN mkdir /pg-backup-dir
RUN mkdir /pg-backup-scrips
RUN mkdir /pg-backup-scrips/host
RUN mkdir /pg-backup-log

WORKDIR /pg-backup-scrips
COPY pg_backup2_example.sh .
COPY pg_restore_example.sh .
COPY pgrestore.sql .
COPY README.md .
RUN chmod +x pg_backup2_example.sh
RUN chmod +x pg_restore_example.sh
RUN chmod 0744 pg_backup2_example.sh
RUN chmod 0744 pg_restore_example.sh
RUN chmod 0744 pgrestore.sql

ENV DATABASE_URL=postgres://absys:absys@absys-db/absys

# Giving permission to crontab file
RUN chmod 0644 /etc/cron.d/container_cronjob

# Running crontab
RUN crontab /etc/cron.d/container_cronjob

# Creating entry point for cron 
ENTRYPOINT ["cron", "-f"]